name: phr
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.2+1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  get: 4.6.6
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.2
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  numberpicker: ^2.1.2
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  screenshot: ^3.0.0
  share_plus: ^9.0.0
  syncfusion_flutter_charts: ^25.2.6
  web_socket_channel: ^3.0.0

dev_dependencies:
  analyzer: null
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
